name: Build and Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build static site
        run: npx vite build
        env:
          NODE_ENV: production
          VITE_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          VITE_GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          VITE_BIOGRAPHY_DOC_ID: ${{ secrets.BIOGRAPHY_DOC_ID }}
          VITE_PHOTOS_FOLDER_ID: ${{ secrets.PHOTOS_FOLDER_ID }}
          VITE_MUSIC_FOLDER_ID: ${{ secrets.MUSIC_FOLDER_ID }}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public